# Generated by Django 5.2.4 on 2025-07-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='decision_app.workflow'),
            preserve_default=False,
        ),
    ]
